version: "2.3"

services:
    balancer-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          PREFIX: ${PREFIX:-~/.local}
          CCACHE_DIR: /balancer/.ccache
          CORES_DIR: /cores
        volumes:
          - .:/balancer:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /balancer
        entrypoint:
          - ./tests/run_as_user.sh
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
