openapi: "3.0.2"
info:
    title: Load Balancer API
    version: "1.0"
servers:
    - url: http://localhost:8080/
components:
    schemas:
        error:
            type: object
            properties:
                detail:
                    description: error message
                    type: string
                    required: true
paths:
  /v1/compress:
    post:
      description: Compressing music
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
  /v1/imalive:
    put:
      description: I am alive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  description: Url of server
                  type: string
                  required: true